### ISSUE TITLE
The project MUST publish the process for reporting vulnerabilities on the project site.

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/community#11]
From the OpenSSF Best Practice requirements:

1. The project MUST publish the process for reporting vulnerabilities on the project site. (URL required) 
1. If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private.

Example: https://github.com/helm/community/blob/main/SECURITY.md

**Comment by TerryHowe** [comment]
Need to create a `SECURITY.md` file for each repo pointing to the documenation.

**Comment by TerryHowe** [comment]
Done
