### ISSUE TITLE
Proposal: Create a new `oras-credentials-go` repository

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/community#24]
As discussed in the community meeting on https://github.com/oras-project/oras-go/discussions/413, we are going to create a repository  `oras-project/oras-credentials-go` for developing a golang SDK to access docker-formatted credentials for `oras-go` v2.

I also proposing that the new SDK repo can be maintained by the same crew of `oras-go`.

**Comment by FeynmanZhou** [comment]
This proposal has been discussed and approved in the [community meeting on Jan 31](https://hackmd.io/P-O6n222TcSMoJgHmTTduw?view#Meeting-Notes). According to the [ORAS governance doc](https://github.com/oras-project/community/blob/main/governance/GOVERNANCE.md), @shizhMSFT as an org owner can create this new repository as a subproject. 

The remaining items for this proposal are to define the governance process and subproject owners/maintainers for this new repo. I will raise a PR to add the related documents to the ORAS governance doc.

**Comment by SteveLasker** [comment]
LGTM
