### ISSUE TITLE
Intent to step down (org owner and sub projects)

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/community#32]
As I previously stated [here](https://github.com/oras-project/oras-go/issues/415#issuecomment-1396182992), I think it's best for me to step down as a maintainer due to inactivity etc.

Opening this issue as documented in the [governance doc](https://github.com/oras-project/community/blob/main/governance/GOVERNANCE.md#subproject-owners).

Please let me know if anything else required. Thank you!

**Comment by shizhMSFT** [comment]
Closed by
- https://github.com/oras-project/oras/pull/866
- https://github.com/oras-project/community/pull/44
- https://github.com/oras-project/oras-go/pull/459
- https://github.com/oras-project/oras-www/pull/124
- https://github.com/oras-project/oras-py/pull/83
