### ISSUE TITLE
Proposal: Create a new `oras-dotnet` repository

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/community#38]
As mentioned by https://github.com/oras-project/oras/issues/774, the LFX program [CNCF - ORAS: Develop .NET SDK for ORAS](https://mentorship.lfx.linuxfoundation.org/project/5d331c88-fc2d-4635-a92c-5d25fb42f47d) is started with the following mentee and mentors.

Mentee:
- @sammychinedu2ky

Mentors
- @Wwwsylvia 
- @shizhMSFT 

To develop the .NET SDK for ORAS, we propose to create a repository `oras-project/oras-dotnet` with the following initial maintainers:

- @sammychinedu2ky
- @shizhMSFT
- @Wwwsylvia 

@sajayantony @SteveLasker @TerryHowe @sabre1041 Could you reply a `+1` to approve this proposal?

**Comment by sajayantony** [comment]
+1 LGTM

**Comment by FeynmanZhou** [comment]
+1 LGTM

**Comment by TerryHowe** [comment]
+1 LGTM

**Comment by toddysm** [comment]
The steps are:
- @shizhMSFT to clearly list who the maintainers will be for the repository
- Maintainers to vote on the approval
- After approval
  - Create GH Team with the maintainers in it
  - Create a repo with README, LICENSE, .gitignore, CODEOWNERS and MAINTAINERS file (CODEOWNERS and MAINTAINERS files contain the maintainers as approved above)
  - Assign the GH Team to own the repository

**Comment by sajayantony** [comment]
Consider using  [https://github.com/cncf/project-template](https://github.com/cncf/project-template)

**Comment by shizhMSFT** [comment]
> Consider using https://github.com/cncf/project-template

I would like to adapt the project template from `oras-go`.

**Comment by shizhMSFT** [comment]
Created repository [oras-project/oras-dotnet](https://github.com/oras-project/oras-dotnet) :tada:

The next steps are creating `CODEOWNERS`, `MAINTAINERS` files, and updating `README`.

**Comment by SteveLasker** [comment]
Thanks @shizhMSFT for updating the issue with the list of maintainers of the proposed `oras-dotnet` sub-project.

To assure we're adhering to our new discussion of a sub-project having clear scope, can I suggest the following:

Merge PR #36 as it creates a list of sub-projects and repos

We also need to capture decision of the org-maintainers to adopt the sub-project, with it's definition.
The problem with GitHub Issues, is we have text LGTMs, that were made before the issue description was updated.
Personally, I'm ok with us moving forward with the `oras-dotnet` repo as it appears you've already created it.
But, lets please merge PR #36 and add the new `oras-dotnet` repo to that file with a new PR.

**Comment by sabre1041** [comment]
+1 LGTM from me as well. I will +1 @shizhMSFT set of next steps so that the proper contents of the repository are in place prior to any project content to ensure proper governance is in place

**Comment by shizhMSFT** [comment]
Closed by
- https://github.com/oras-project/oras-dotnet/pull/1
- https://github.com/oras-project/oras-dotnet/pull/2
