### ISSUE TITLE
Proposing Andrew Block as a project maintainer

### ISSUE THREAD

**Issue by toddysm** [oras-project/community#39]
As per the conversations that we had in the last ORAS Community call, I would like to propose @sabre1041 (Andrew Block) as a maintainer for the ORAS organization. Here are some details about Andrew and his involvement in ORAS and the OSS communities.

- Andrew attended the ORAS community meetings 11 times since July, 2022
- He also his [commits to ORAS](https://github.com/oras-project/oras-go/commits?author=sabre1041)

Here are also some words from Andrew why he thinks he will be a good maintainer of the ORAS project.

---------------------------
Hello,

During the most recent ORAS community meeting on 28 February 2023 [1], I was proposed as a new organization maintainer of the ORAS project. To support this nomination, I wanted to share how I have been able to contribute to the project thus far and how I will help ensure that it is a prosperous project moving forward.

I am an active member of the Open Source and cloud native community and not only act as a maintainer on other CNCF affiliated projects, but also help shephard principles and practices within the Open Source community and within organizations globally through my affiliation with Red Hat.

One such consumer of the ORAS project is Helm, the de facto package manager for Kubernetes, for which I am a core maintainer. My primary focus and ownership within the Helm project is supporting the ecosystem surrounding the ability to leverage OCI registry as first class citizens for storing Helm charts. I helped bring this capability to GA early in my tenure as maintainer after it was in "experimental" status for several years. During this time, I worked frequently with members of the ORAS community to build functionality into the v1 branch for which Helm makes use of as well as to provide test coverage and features to the current v2 main branch.

Since that time, I have become more involved in the ORAS community and am a frequent participant in the weekly community meetings. By getting more deeply involved in the ORAS community, I began to see how the capabilities produced by the project could be used outside of the Helm ecosystem. One such example is the use of ORAS within the Emporous (formerly called Universal Object Reference [UOR]) as a way to manage content within OCI registries [2].

Outside of direct contributions through code, I enjoy helping build communities. Within my professional career at Red Hat, I lead the Red Hat Community of Practice program which brings together individuals of common interests so that they may be able to collaborate together and share their knowledge with others. In the Open Source community, I enjoy participating in a wide range of venues including presenting in both virtual and in person events. I have presented on the use of ORAS within the Emporous and ORAS projects at smaller events, such as DevConf.US [3], to large scale conferences including multiple appearances at KubeCon [4]. The work as a community champion is my primary role within the Emporous community and is the focus of a new working group within the ORAS project focusing on the ability to provide a search API for OCI registries.

Finally, my nomination as an organization maintainer to the ORAS project is being supported by Josh Dolitsky, who will be stepping down as a maintainer himself. There are a lot of synergies that we share including participating in similar Open Source projects as well as each being maintainers on the Helm project. By having me provide the same skillsets and representation from one of the biggest consumers of ORAS (Helm), it will ensure the connection between each project remains strong.

I'd be happy to address any questions or concerns related to any of the content contained within this note and look forward to an upcoming decision from the ORAS community related to my nomination.

Thank you,
Andrew Block

[1] - [https://hackmd.io/P-O6n222TcSMoJgHmTTduw#Next-meeting-Feb-28-2023-400-PM--500-PM-PST](https://hackmd.io/P-O6n222TcSMoJgHmTTduw#Next-meeting-Feb-28-2023-400-PM--500-PM-PST)
[2] - [https://emporous.io](https://emporous.io)
[3] - [https://www.youtube.com/watch?v=6fohG10y3z0&t=2004s](https://www.youtube.com/watch?v=6fohG10y3z0&t=2004s)
[4] - [https://www.youtube.com/watch?v=mgKSq7ekJJI](https://www.youtube.com/watch?v=mgKSq7ekJJI)

----------------------------

At the moment Andrew is not a maintainer on any of the ORAS sub-projects. The request for maintainers (@sajayantony, @jdolitsky, @SteveLasker, @shizhMSFT, @deitch) is to add their comments and vote on Andrew's nomination.

**Comment by sajayantony** [comment]
+1 and LGTM. Thank you @sabre1041

**Comment by SteveLasker** [comment]
+1. 
As mentioned in the ORAS community meeting, I'd suggest closing this, and make a PR adding @sabre1041 to [OWNERS.md](https://github.com/oras-project/community/blob/main/OWNERS.md) and [CODEOWNERS](https://github.com/oras-project/community/blob/main/CODEOWNERS). The reasoning above can be in the PR. 

Using this issue to propose Andrew means the maintainers must first +1 this issue, then make a PR to vote again. 
This allows the ORAS Maintainers to vote once, streamlining the process.

**Comment by shizhMSFT** [comment]
+1 and LGTM. Welcome @sabre1041!

**Comment by scottrigby** [comment]
+1 nb 🙂

**Comment by SteveLasker** [comment]
A note to process above:
Personally, I find the issue for every PR process overhead. For larger, gnarly designs, or larger work items, I can definitely see the value in creating an issue before the PR.
For one liners, that are known and defined, this feels like a lot of overhead.

My suggestion is two-fold:
1. create a contributors guide for what process should be followed. If the maintainers feels every PR should have an Issue, that's the maintainer's decision.
2. Lets get Andrew and Terry added, so we have enough active folks to act upon the above.

**Comment by SteveLasker** [comment]
merged, contrats @sabre1041
