### ISSUE TITLE
Nominate Terry Howe to become an ORAS org owner

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/community#42]
Hi,

I would like to nominate @TerryHowe Terry Howe to become an ORAS org owner. I believe Terry is qualified for this role. Here are some metrics about Terry and his involvement and contributions to ORAS. 

- Terry started to contribute to ORAS in Dec 2022. Terry has been promoted to a subproject maintainer on Feb 21, see [PR](https://github.com/oras-project/oras/pull/821)
- Terry raised 19 PRs in multiple ORAS repositories (ORAS CLI, ORAS-go, and ORAS-www) and is currently ranking at 2 in the last quarter. [PRs Authors Table - Grafana (cncf.io)](https://oras.devstats.cncf.io/d/22/prs-authors-table?orgId=1&var-period_name=Last%20quarter&var-repogroup_name=All)
- Terry reviewed PRs in multiple ORAS repositories actively and [left 126 comments in the last quarter](https://oras.devstats.cncf.io/d/29/pr-reviews-by-contributor?orgId=1&var-period=q&var-repo_name=All&var-reviewers=%22TerryHowe%22). 
- Terry attends the ORAS community call 3 times since Jan 2023, see [meeting notes](https://hackmd.io/P-O6n222TcSMoJgHmTTduw?view). 
- Terry is active to provide support and response to users in the ORAS Slack channel in the last quarter.

I hope @sajayantony, @jdolitsky, @SteveLasker, @shizhMSFT, and @deitch could add your comments and vote on Terry's nomination.

**Comment by shizhMSFT** [comment]
+1. LGTM. Terry has been very active in the last months across multiple repositories in the ORAS org. Meanwhile, Terry contributed code with high quality and influenced the projects to be developed in a good direction.

**Comment by SteveLasker** [comment]
+1 to adding Terry as a great addition to the ORAS Project

**Comment by SteveLasker** [comment]
@sajayantony can you please review?

**Comment by sabre1041** [comment]
+1 to adding Terry. He has been active across ORAS organizations but in addition participating in other areas that are currently making use the ORAS project (such as Helm)
