### ISSUE TITLE
[GitVote] Test Issue

### ISSUE THREAD

**Issue by sajayantony** [oras-project/community#50]
Testing git vote 
/vote-maintainers

**Comment by TerryHowe** [comment]
it would be nice if gitvote automatically populated with the 3 choices

**Comment by sajayantony** [comment]
@TerryHowe can you describe what you would like to see here. @caniszczyk and @tegioz might be interested in feedback.

**Comment by TerryHowe** [comment]
![Screen Shot 2023-04-20 at 07 32 07](https://user-images.githubusercontent.com/104113/233382226-a0b645d2-b273-4598-bd59-24d9e7d9ef17.png)

Actually setting the 3 emoticons on the post instead of just the log so people can just click on them rather than the first person has to set.

**Comment by TerryHowe** [comment]
Done I think
