### ISSUE TITLE
Request for krustlet/oci-distribution to move under the `oras-project` org

### ISSUE THREAD

**Issue by thomastaylor312** [oras-project/community#59]
Due to the upcoming archival of the Krustlet project (https://github.com/krustlet/krustlet/issues/758), the `oci-distribution` Rust crate (https://github.com/krustlet/oci-distribution) needs a new home in the CNCF. This project is actively maintained by myself and @flavio and is used across various CNCF projects like wasmCloud and Kubewarden, ByteCode Alliance projects, and other open source projects like Spin and Kata Containers.

I would like to propose that we move the `oci-distribution` crate to the ORAS project

**Comment by shizhMSFT** [comment]
There is a repo [`oras-rs`](https://github.com/oras-project/oras-rs) in the ORAS project. May I consider `krustlet/oci-distribution` is a successor of `oras-rs`?

**Comment by FeynmanZhou** [comment]
> There is a repo [`oras-rs`](https://github.com/oras-project/oras-rs) in the ORAS project. May I consider [`krustlet/oci-distribution`](https://github.com/krustlet/oci-distribution) is a successor of `oras-rs`?

Same question. 

It looks like the sub-folder oci-distribution in oras-rs is similar with [krustlet/oci-distribution](https://github.com/krustlet/oci-distribution). https://github.com/oras-project/oras-rs/tree/main/krustlet/crates/oci-distribution.

What's the long-term plan of krustlet/oci-distribution](https://github.com/krustlet/oci-distribution) project?

@thomastaylor312  
Would you mind joining the ORAS community meeting at 17:00 PM on May 28 for further discussion?

**Comment by flavio** [comment]
Hello, I'm one of the maintainers of `krustlet/oci-distribution`. I'm based in Italy, I will not be able to join the community call because it takes places at 2AM local time.

I personally care about this crate because it's one of the dependencies of [Kubewarden](https://kubewarden.io), another CNCF project I maintain.

Feature wise, I think `oci-distribution` is doing well. We've always been open to community contributions. For example, we recently got some PRs from the community introducing small improvements
.
The codebase is well documented (both inline docs and public API docs), it has unit tests and is regularly linted. We're using GitHub Actions to run checks on PRs and to perform releases, including publishing on [crates.io](https://crates.io/crates/oci-distribution).

There's some code cleanup we could do. I would love to drive it once I have some spare time.

**Comment by thomastaylor312** [comment]
I'll be addressing this tonight in the community call, but some responses here as well:

> There is a repo [oras-rs](https://github.com/oras-project/oras-rs) in the ORAS project. May I consider [krustlet/oci-distribution](https://github.com/krustlet/oci-distribution) is a successor of oras-rs?

This is not a successor to oras-rs per se. `oci-distribution` is a fully featured OCI client library that is used both for pulling normal container images as well as artifacts. Whether or not that is seen as a successor to `oras-rs` I think is up to the community, but I think they are different (if not related) things. Another difference is that `oras-rs` imported this project as a subtree, which I assume was to build something on top of it.

> What's the long-term plan of [krustlet/oci-distribution](https://github.com/krustlet/oci-distribution) project?

The long term plan is continued maintenance and improvement as @flavio mentioned. This project is a key part of various projects within the ecosystem, especially (but not only) in the wasm space. The new [OCI wasm artifact spec](https://tag-runtime.cncf.io/wgs/wasm/deliverables/wasm-oci-artifact/) has a crate that wraps this one and is [moving to](https://github.com/bytecodealliance/governance/issues/88) the Bytecode alliance. Other CNCF projects like kubewarden and wasmCloud are large downstream consumers of this crate as well. So it is safe to say that this crate will be maintained and used for the foreseeable future

**Comment by FeynmanZhou** [comment]
> As part of the move, we should probably rename the repo as `rust-oci-distribution` for clarity sake

`distribution` sounds overlapping with the OCI registry project [distribution/distribution](https://github.com/distribution/distribution). How about `oci-rust-client` ?

**Comment by thomastaylor312** [comment]
I'm ok calling the repo `oci-rust-client`! However, as discussed in the community call, the crate will still need to be called `oci-distribution` for backwards compatibility reasons. We can't redirect an old crate to a new one so it would be a breaking change to downstream dependencies. Will that be ok?

**Comment by squillace** [comment]
if there's no conflicting crate name, that **should** be ok.... right?

**Comment by thomastaylor312** [comment]
Yeah it isn't so much about a conflict so much as everyone needing to update their actual dependency name in Cargo.toml and across their code

**Comment by flavio** [comment]
I'm totally fine with the rename

**Comment by astoycos** [comment]
I just wan't to chime in here and +1 on oci-distribution's usefulness, we use it in the [bpfman.io](bpfman.io) project in order to package eBPF programs in OCI Images and overall have had a great experience with the crate + community 🎆

**Comment by FeynmanZhou** [comment]
@SteveLasker @sabre1041 Would you mind leaving your opinions for this proposal? Org maintainers' opinion should be involved.

**Comment by SteveLasker** [comment]
Apologies for not voting in time as I missed the notifications. 
I support the addition while noting the current name `oci-distribution` sounds like it's yet another server-side implementation specific to crates. "Naming is hard". 
It looks like @flavio believes the rename is possible, which I'd also support, but wouldn't block on that if it's a huge impact. 

+1 to adding under the oras-project

**Comment by thomastaylor312** [comment]
Once the vote passes, I am going to:

1. Rename the repo in its current org to `rust-oci-client`
2. Initiate the transfer
3. Update the Readme and Cargo.toml with new links
4. Open an issue to get feedback about renaming the crate itself from our downstream users

Does that sound like an ok plan moving forward?

**Comment by sabre1041** [comment]
Also apologies for the delay. First and foremost, +1 to adding the repository underneath the [oras-project](https://github.com/oras-project) organization. 

As for your plan with the repo rename and transfer, that also is a sensible approach as well. it would remove the dependency on actions that you would need to take and enable the community to determine the final resting place. 

It might be good to add a note to the `README.md` indicating the project its currently in a transition phase so there are no misconceptions for those coming across it

**Comment by thomastaylor312** [comment]
Hi friends! Just wanted to ping here and see what we needed to do about officially accepting this project in as the official git vote failed due to not enough votes, but there appears to be general consensus

**Comment by FeynmanZhou** [comment]
@TerryHowe Thanks for setting up the new repo for transferring it. I saw it is still a private repo. Should we make it public?

**Comment by FeynmanZhou** [comment]
> Hi friends! Just wanted to ping here and see what we needed to do about officially accepting this project in as the official git vote failed due to not enough votes, but there appears to be general consensus

@thomastaylor312 This request got the majority of approvals from ORAS org maintainers @oras-project/oras-org-maintainers now. It means we are good to accept oci-rust-client as a new project. We had a decision made on [Jun 2024's community meeting](https://hackmd.io/P-O6n222TcSMoJgHmTTduw?view#Jun-11-2024). You can ignore the git vote result above as this process is not effective.

**Comment by squillace** [comment]
YAY!!! I'm getting ready, pending this acceptance, to archive the CNCF's Krustlet project.

**Comment by TerryHowe** [comment]
I was thinking make in public as soon as it is some vague ready state.

**Comment by FeynmanZhou** [comment]
I think we may need to transfer the [krustlet/oci-distribution](https://github.com/krustlet/oci-distribution) from Krustlet to ORAS org instead of pushing the code to a new repo. See https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository.

**Comment by thomastaylor312** [comment]
Yeah we need to transfer preferably. I'll work on renaming the repo first as promised

**Comment by thomastaylor312** [comment]
Repo has been transferred! https://github.com/oras-project/rust-oci-client
